### ISSUE TITLE
Adding a new Solr Core 

### ISSUE THREAD

**Issue by kirchnerf** [Daniel-KM/Omeka-S-module-SearchSolr#8]
When adding a new Core in Omeka-S admin web gui I get the following error message

> ArgumentCountError
> Too few arguments to function Doctrine\ORM\PersistentCollection::__construct(), 0 passed in /data/srv/www/htdocs/omeka-s/modules/SearchSolr/src/Entity/SolrCore.php on line 83 and exactly 3 expected
> 
> Details:
```
ArgumentCountError: Too few arguments to function Doctrine\ORM\PersistentCollection::__construct(), 0 passed in /data/srv/www/htdocs/omeka-s/modules/SearchSolr/src/Entity/SolrCore.php on line 83 and exactly 3 expected in /data/srv/www/htdocs/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php:107
Stack trace:
#0 /data/srv/www/htdocs/omeka-s/modules/SearchSolr/src/Entity/SolrCore.php(83): Doctrine\ORM\PersistentCollection->__construct()
#1 /data/srv/www/htdocs/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(317): SearchSolr\Entity\SolrCore->__construct()
#2 /data/srv/www/htdocs/omeka-s/application/src/Api/Manager.php(224): Omeka\Api\Adapter\AbstractEntityAdapter->create()
#3 /data/srv/www/htdocs/omeka-s/application/src/Api/Manager.php(78): Omeka\Api\Manager->execute()
#4 /data/srv/www/htdocs/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(99): Omeka\Api\Manager->create()
#5 /data/srv/www/htdocs/omeka-s/modules/SearchSolr/src/Controller/Admin/CoreController.php(91): Omeka\Mvc\Controller\Plugin\Api->create()
#6 /data/srv/www/htdocs/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): SearchSolr\Controller\Admin\CoreController->addAction()
#7 /data/srv/www/htdocs/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#8 /data/srv/www/htdocs/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#9 /data/srv/www/htdocs/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
#10 /data/srv/www/htdocs/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch()
#11 /data/srv/www/htdocs/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#12 /data/srv/www/htdocs/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#13 /data/srv/www/htdocs/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#14 /data/srv/www/htdocs/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#15 {main}
```

The "add-core-form" only consists of the field 'Name'.
Tested on:

- Omeka-S version: 3.0.1
- SearchSolr version: 3.5.16.3 and 3.5.19.3
- Search version: 3.5.16.3 and 3.5.18.3

**Comment by Daniel-KM** [comment]
Thanks, it is fixed.
